version: '3'

services:
  api_dev:     
    image: tadrianonet/apidestaques 
    ports:
      - "5000:80"
    links:
      - link-db
  link-db:      
    container_name: link-db   
    image: tutum/mongodb 
    ports:
      - "27017:27017"
      - "28017:28017"   
    environment:
      - AUTH=no